/***********************************************************************
   WARNING: This file generated by robots.  Do not attempt to modify.

   This API is for use with assets.db
   Which contains 0 table(s).
***********************************************************************/

#include "D:\dev\snesquest\libsnes/assets.h"
#include "DB.h"
#include "libutils/CheckedMemory.h"
#include "sqlite/sqlite3.h"


struct DB_assets{
   DBBase base;
};

DB_assets *db_assetsCreate(){
   DB_assets *out = checkedCalloc(1, sizeof(DB_assets));
   return out;
}

void db_assetsDestroy(DB_assets *self){
   dbDestroy((DBBase*)self);
   checkedFree(self);
}

int db_assetsCreateTables(DB_assets *self){
   int result = 0;


   return DB_SUCCESS;
}

