/***********************************************************************
   WARNING: This file generated by robots.  Do not attempt to modify.

   This API is for use with assets.db
   Which contains 0 table(s).
***********************************************************************/

#pragma once

#include "libutils/Defs.h"
#include "libutils/String.h"

typedef struct sqlite3_stmt sqlite3_stmt;
typedef struct lua_State lua_State;
typedef struct DB_assets DB_assets;

DB_assets *db_assetsCreate();
void db_assetsDestroy(DB_assets *self);
int db_assetsCreateTables(DB_assets *self);

