/***********************************************************************
   WARNING: This file generated by robots.  Do not attempt to modify.

   This API is for use with DBAssets.db
   Which contains 0 table(s).
***********************************************************************/

#pragma once

#include "libutils/Defs.h"
#include "libutils/String.h"

typedef struct sqlite3_stmt sqlite3_stmt;
typedef struct lua_State lua_State;
typedef struct DB_DBAssets DB_DBAssets;

DB_DBAssets *db_DBAssetsCreate();
void db_DBAssetsDestroy(DB_DBAssets *self);
int db_DBAssetsCreateTables(DB_DBAssets *self);

