/***********************************************************************
   WARNING: This file generated by robots.  Do not attempt to modify.

   This API is for use with DBAssets.db
   Which contains 0 table(s).
***********************************************************************/

#include "D:\dev\snesquest\libsnes/DBAssets.h"
#include "DB.h"
#include "libutils/CheckedMemory.h"
#include "sqlite/sqlite3.h"


struct DB_DBAssets{
   DBBase base;
};

DB_DBAssets *db_DBAssetsCreate(){
   DB_DBAssets *out = checkedCalloc(1, sizeof(DB_DBAssets));
   return out;
}

void db_DBAssetsDestroy(DB_DBAssets *self){
   dbDestroy((DBBase*)self);
   checkedFree(self);
}

int db_DBAssetsCreateTables(DB_DBAssets *self){
   int result = 0;


   return DB_SUCCESS;
}

